# Generated by Django 4.1.1 on 2022-09-29 18:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('HEAVY', 'HEAVY'), ('ASSAULT_RIFLE', 'ASSAULT_RIFLE'), ('PISTOL', 'PISTOL')], max_length=100)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='weapons_images')),
            ],
        ),
    ]
