# Generated by Django 4.1.1 on 2022-09-30 09:57

from django.db import migrations, models
import weapons.constants


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0002_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('PACKAGING', 'PACKAGING'), ('DELIVERED', 'DELIVERED'), ('CANCELLED', 'CANCELLED')], default=weapons.constants.OrderStatus['PENDING'], max_length=100),
        ),
    ]
